# Generated by Django 4.2.3 on 2023-08-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table='advertisements',
        ),
    ]
